apiVersion: apps/v1
kind: Deployment

metadata:
  name: spring-app-deployment

spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: spring-app

  template:
    metadata:
      labels:
        app: spring-app

    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: spring-app
          image: spring-app:latest
          ports:
            - containerPort: 8080

          lifecycle:
             preStop:
               exec:
                 command: ["sh", "-c", "sleep 10"]

          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10			  
